# =====================================================
# CARECOMPANION ANDROID - GRADLE SETTINGS
# =====================================================

# Gradle JVM memory
org.gradle.jvmargs=-Xmx1536m

# Use AndroidX
android.useAndroidX=true

# =====================================================
# LOCAL AAPT2
# =====================================================
# Use the AAPT2 executable already installed in the
# Android SDK instead of downloading AAPT2 from Maven.

android.aapt2FromMavenOverride=C:/Users/op354/AppData/Local/Android/Sdk/build-tools/36.0.0/aapt2.exe

# =====================================================
# GRADLE NETWORK SETTINGS
# =====================================================

systemProp.org.gradle.internal.http.connectionTimeout=120000
systemProp.org.gradle.internal.http.socketTimeout=120000

systemProp.https.protocols=TLSv1.2,TLSv1.3

# =====================================================
# GRADLE
# =====================================================

org.gradle.daemon=true